config/routes.rb
Itpact::Application.routes.draw do
  devise_for :admins
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :products
  resources :reviews, :line_items, :carts, :pages, :orders
  resources :sections, :brands, :vars, :deliveries 

  get "pay/congratulations"
  get "pay/attention"
  match '/pages' => 'pages#index'
  match '/pages/:id' => 'pages#show'
  root :to => 'sections#show', :id => '1'
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
   has_many :line_items, dependent: :destroy

   def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
  <table width="100%">
  <%= render(cart.line_items) %>
  <tr class="total_line">
    <td colspan="2">Всего: </td>
    <td class="total_cell"><strong><%= number_to_currency(cart.total_price) %></strong></td>
  </tr>
</table>
<br>
<div style="font-color:#000000;">
	<%= button_to 'Очистить корзину', cart, method: :delete, :class => 'btn', remote: true %>
    <%= button_to "Оформить заказ", new_order_path, method: :get, :class => 'btn btn-warning' %>
</div>

app/views/carts/_form.html.erb
<%= form_for @cart, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                carts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$("#notice").hide();

$('#cart').html('<%=j render @cart %>');

{ $('#cart').hide('blind', 1000); }

app/views/carts/edit.html.erb
<%- model_class = Cart -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/carts/index.html.erb
<%- model_class = Cart -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to cart.id, cart_path(cart) %></td>
        <td><%=l cart.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cart_path(cart), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cart_path(cart),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cart_path,
            :class => 'btn btn-primary' %>

app/views/carts/new.html.erb
<%- model_class = Cart -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<%= render(@cart) %>