config/routes.rb
Itpact::Application.routes.draw do
  devise_for :admins
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :products
  resources :reviews, :line_items, :carts, :pages, :orders
  resources :sections, :brands, :vars, :deliveries 

  get "pay/congratulations"
  get "pay/attention"
  match '/pages' => 'pages#index'
  match '/pages/:id' => 'pages#show'
  root :to => 'sections#show', :id => '1'
  

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
# GET /reviews
  # GET /reviews.json
  def index
    if admin_signed_in?
      @reviews = Review.all
    else
      @reviews = Review.where(product_id:(params[:product_id])).scoped 
      @review = Review.new(:parent_id => params[:parent_id], product_id:(params[:product_id]))
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    review_parent = Review.find(params[:parent_id])
    @review = Review.new(parent_id: params[:parent_id], product_id: review_parent.product_id)


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end


  private
    

    def correct_user
      if user_signed_in?
        @review = current_user.reviews.find_by_id(params[:id])
        
      end
    end	

  

app/helpers/reviews_helper.rb
module ReviewsHelper
	def nested_reviews(reviews)
    reviews.map do |review, sub_reviews|
      render(review) + content_tag(:div, nested_reviews(sub_reviews), :class => "nested_reviews")
    end.join.html_safe
  end
end

app/views/reviews/_form.html.erb
<%= form_for @review, :html => { :class => 'form-horizontal' } do |f| %>
   <% if user_signed_in? %>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>
  
      <%= f.hidden_field :product_id, value: params[:product_id] %>
    
      <%= f.hidden_field :user_id, value: current_user.id %>
   
      <%= f.hidden_field :parent_id %>

  <div class="form-actions">
    <%= f.submit "Написать отзыв", :class => 'btn btn-primary' %>
  </div>
  <% else %>
  <p>Оставлять отзывы могут только зарегистрированные пользователи.
    Если вы уже зарегистрированы,  <%= link_to "входите", new_user_session_path %>.</p>
  <% end %>
<% end %>

app/views/reviews/_review.html.erb
<% if user_signed_in? %>
  <% if review.user_id == current_user.id %>
    <div class="review_stop">
  <% else%>
    <% if review.ancestry == nil%>
      <div class="review_root">
    <% else %>
      <div class="review">
    <% end %>
  <% end %>  
<% else%>
  <% if review.ancestry == nil%>
    <div class="review_root">
  <% else %>
    <div class="review">
  <% end %>
<% end %>
  <div class="created_at"><%= review.created_at.strftime("%d-%m-%Y в %H:%M:%S") %></div>
  <div class="content">
    <%= link_to review.content, review %>
  </div>
  <div class="actions">
    <% if review.user.username != nil %>
    <%= review.user.username %>
    <% end %>
    <br>
    <%= link_to "Ответить", new_review_path(:parent_id => review, :product_id => review.product_id) %>
    <% if user_signed_in? %>
      <% if review.user_id == current_user.id %>
      | <%= link_to "Удалить", review, :confirm => "Вы уверены?", :method => :delete %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/reviews/edit.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/index.html.erb
<ul class="breadcrumb">
  <div class="container">
    <div class="row">
      <div class="span12">
		<h1>Отзывы</h1>
		<br />
		<% if admin_signed_in? %>
		  <tbody>
            <% @reviews.each do |review| %>
		      <tr>
		      <td><%= link_to review.id, review_path(review) %></td>
		      <td><%= review.product_id %></td>
		      <td><%= review.user_id %></td>
		      <td><%= review.content %></td>
		      <td>
		    <% end %>	
		<% else %>
		<%= nested_reviews @reviews.arrange(:order => :created_at) %>
		<% end %>
		<br />
		<%= render "form" %>
		<br />
      </div>
    </div>  
  </div>
</ul>  

app/views/reviews/new.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/show.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @review.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @review.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @review.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reviews_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_review_path(@review), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              review_path(@review),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>