config/routes.rb
Itpact::Application.routes.draw do
  devise_for :admins
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :products
  resources :reviews, :line_items, :carts, :pages, :orders
  resources :sections, :brands, :vars, :deliveries 

  get "pay/congratulations"
  get "pay/attention"
  match '/pages' => 'pages#index'
  match '/pages/:id' => 'pages#show'
  root :to => 'sections#show', :id => '1'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable  

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  # attr_accessible :title, :body
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :name

  belongs_to :product
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
   has_many :line_items, dependent: :destroy

   def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  attr_accessible :city, :how, :price
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :status, :user_id, :address, :email, :full_name
  has_many :line_items, dependent: :destroy

  after_save :popular_and_novelty_calculation

  def popular_and_novelty_calculation
    var = Var.first
  	products = Product.all
  	products.each do |product|
  	  col = 0	
      line_items = LineItem.where product_id:(product.id)
      if product.novelty == true
      	if product.novelty_at < Date.today.advance(:days => - var.novelty_duration)
      	  product.update_attribute(:novelty, "false")
        end
      end
      if product.popular_lock == false  	
        line_items.where("created_at > ?", Time.zone.now.advance(:days => - var.novelty_period)).each do |line_item|
          col = col + line_item.quantity 
        end
        if col > product.popular_sale
          product.update_attribute(:popular, true)
        end
      end  
    end
  end




  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end  
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :article, :brand_id, :delivery_method, :description, :function, :image_link, :name, :novelty, :novelty_at, :novelty_change_at, :novelty_force, :novelty_margin, :price, :section_id, :popular, :popular_lock, :product_images_attributes
  has_many :line_items
  has_many :reviews, dependent: :destroy
  has_many :product_images, :dependent => :destroy  
  accepts_nested_attributes_for :product_images, :allow_destroy => true

  def self.text_search(query)
    if query.present?
      where "to_tsvector('russian', name) @@ to_tsquery('russian', :q) or to_tsvector('russian', description) @@ to_tsquery('russian', :q)", q: query     
    else
      scoped
    end
  end 

  before_destroy :ensure_not_referenced_by_any_line_item
  
  private

  #убеждаемся в отсутствии товарных позиций,
  #ссылающихся на данный товар

  

  # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end	

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  attr_accessible :image, :product_id
  mount_uploader :image, ImageUploader
  belongs_to :product, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :content, :product_id, :user_id, :ancestry, :parent_id
  has_ancestry
  belongs_to :user
  belongs_to :product
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :name, :parent_id

  has_many :products
  belongs_to :product

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :full_name, :address, :confirmed_at, :provider, :uid  
  # attr_accessible :title, :body
  has_many :reviews, dependent: :destroy

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end    
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/models/var.rb
class Var < ActiveRecord::Base
  attr_accessible :novelty_duration, :novelty_period
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pay_helper.rb
module PayHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def nested_reviews(reviews)
    reviews.map do |review, sub_reviews|
      render(review) + content_tag(:div, nested_reviews(sub_reviews), :class => "nested_reviews")
    end.join.html_safe
  end
end

app/helpers/vars_helper.rb
module VarsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="span2">
      <a href="http://webmoney.ru/"><%= image_tag("101.jpg", size:'90x50') %></a>
    </div>
    <div class="span2">
      <a href="https://money.mail.ru/"><%= image_tag("102.gif", size:'90x49') %></a>
    </div>
    <div class="span2">
      <a href='https://www.moneymail.ru/'><%= image_tag("103.jpg", size:'90x50') %></a>
    </div>
    <div class="span2">
      <a href='http://www.libertyreserve.com/'><%= image_tag("104.jpg", size:'90x50') %></a>
    </div>
    <div class="span2">
      <a href='http://liqpay.com/'><%= image_tag("105.jpg", size:'90x50') %></a>
    </div>
    </div>
    <div class="row">
    <div class="span2">
      <a href="http://platezh.ru/"><%= image_tag("106.jpg", size:'90x50') %></a>
    </div>
    <div class="span2">
      <a href='http://w1.ru/'><%= image_tag("107.jpg") %></a>
    </div>
    <div class="span2">
      <a href='http://money.yandex.ru/'><%= image_tag("108.gif") %></a>
    </div>
    <div class="span2">
      <a href='http://card.ruru.ru/'><%= image_tag("109.gif", size:'90x50') %></a>
    </div>
    <div class="span2">
      <a href="http://www.privatbank.ru/"><%= image_tag("110.gif", size:'90x49') %></a>
    </div>
    </div>
    <div class="row">
    <div class="span2">
      <a href='http://sbrf.ru/'><%= image_tag("111.jpg") %></a>
    </div>
    <div class="span2">
      <a href="http://elecsnet.ru/"><%= image_tag("112.gif") %></a>
    </div>
    <div class="span2">
      <a href="http://euroset.ru/"><%= image_tag("113.jpg", size:'120x32') %></a>
    </div>
    <div class="span2">
      <a href="http://novo-plat.ru/"><%= image_tag("114.gif", size:'91x40') %></a>
    </div>
    <div class="span2">
      <a href='http://qiwi.ru/'><%= image_tag("132.gif") %></a>
    </div>
    </div>
    <div class="row">
    <div class="span2">
      <a href='http://www.leadermt.ru/'><%= image_tag("118.jpg", size:'100x40') %></a>
    </div>
    <div class="span2">
      <a href='http://www.contact-sys.com/'><%= image_tag("117.jpg", size:'86x40') %></a>
    </div>
    <div class="span2">
      <a href="http://www.korona.net/"><%= image_tag("119.jpg", size:'100x40') %></a>
    </div>
    <div class="span2">
      <a href="http://www.visa.com"><%= image_tag("120.jpg", size:'64x40') %></a>
    </div>
    <div class="span2">
      <a href='http://www.mastercard.com'><%= image_tag("121.jpg", size:'62x40') %></a>
    </div>
    <div class="span4"></div>  
  </div>
</div>
<hr style="height:2px;color:#555555">
<div class="row">
    <div class="span4"></div>
    <div class="span5">
      <p>
        &copy; 2013 ITPACT &nbsp;&nbsp;<a href="">О компании</a>
        &nbsp;&nbsp;<a href="">Документация</a>
        &nbsp;&nbsp;<a href="">Вакансии</a>
      </p>
    </div>
    <div class="span3"></div>

app/views/layouts/_header.html.erb
  <br>
  <div class="container" style="width: 940px">
    <div class="row">
      <div class="span1"><%= image_tag("main_logo.png", size:"120x34") %></div>
        <div class="span2"><br>
        <h3>Айти-Пакт</h3></div>
        <div class="span9"><p><small>
        &nbsp;&nbsp;<%= link_to "Главная", "/sections/1" %>
        &nbsp;&nbsp;&nbsp;&nbsp;<a href="">Услуги и цены</a>
        &nbsp;&nbsp;&nbsp;&nbsp;<a href="">Документация</a>
        &nbsp;&nbsp;&nbsp;&nbsp;<a href="">Удаленная помощь</a>
        &nbsp;&nbsp;&nbsp;&nbsp;<a href="">Конфигуратор ПК</a>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Программное обеспечение", "/sections/1" %></small>
      </p>

    
    <div class="navbar">
      <div class="navbar-inner">
      
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <%= form_tag pages_path, :class => "navbar-search pull-left", :method => :get do %>
        <%= text_field_tag :query, params[:query], :class => "search-query span4", :placeholder => "Поиск по каталогу" %>
        <% end %>

        <% if user_signed_in? %>   
<ul class="nav nav-pills pull-right">
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><strong>
      <% if current_user.username != "" %>
        <%= current_user.username %>
      <% else %>
        <%= current_user.email %>
      <% end %>  
    </strong> <b class="caret"></b></a>
    <ul id="menu1" class="dropdown-menu">
      <li><%= link_to 'Профиль', edit_user_registration_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Выход", destroy_user_session_path, method: :delete %></li>
    </ul>
  </li>
</ul>        

<% else %>
  
    <div class="nav-collapse pull-right">    
    <ul class="nav">
              
      <li><%= link_to "Регистрация", new_user_registration_path %></li>
      <li><%= link_to "Вход", new_user_session_path %></li>
    </ul>
  </div>

<% end %>
          </div>     
        </div>     
      </div>      
    </div>     
  </div>

app/views/layouts/_managebar.html.erb
<br>
  <div class="container" style="width: 940px">
    <div class="row">
      
        

    
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="#">Админка</a>
      
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        
        <% if admin_signed_in? %>
<ul class="nav nav-pills">  
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Меню<b class="caret"></b></a>
    <ul id="menu2" class="dropdown-menu">
      <li><%= link_to "Товары", products_path %></li>
      <li><%= link_to "Брэнды", brands_path %></li>
      <li><%= link_to "Разделы", sections_path %></li>
      <li><%= link_to "Заказы", orders_path %></li>
      <li><%= link_to "Отзывы", reviews_path %></li>
      <li><%= link_to "Доставка", deliveries_path %></li>
      <li><%= link_to "Переменные", vars_path %></li>
    </ul>
  </li>
</ul>
        <% end %>
        <% if admin_signed_in? %>
<ul class="nav nav-pills pull-right">
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><strong>
        <%= current_admin.email %>  
    </strong> <b class="caret"></b></a>
    <ul id="menu1" class="dropdown-menu">
      <li class="divider"></li>
      <li><%= link_to "Выход", destroy_admin_session_path, method: :delete %></li>
    </ul>
  </li>
</ul>        
<% end %>
          </div>     
        </div>     
      </div>      
    </div>     
  </div>

app/views/layouts/_profooter.html.erb
<div class="span9">
<ul class="breadcrumb">
<div class="container">
    <div class="row">
      
  
    <small>
    <div class="span3">
<% num_column = products_calculation %>
<% num_prod = 0  %>
<% @sections.each do |section| %>
  <strong><%= link_to section.name, section_path(section.id) %></strong><br>
  <% num_prod += 1 %>
  <% if num_prod == num_column %>
    </div>
    <div class="span3">
    <% num_prod = 0 %>
  <% end %>   

  <% section.products.each do |product| %>
    &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to product.name, page_path(product.id) + "?image=1" %><br>
    <% num_prod += 1 %>
    <% if num_prod == num_column %>
    </div>
    <div class="span3">
      <% num_prod = 0 %>
    <% end %>   

  <% end %>
<% end %>
            </div></small>
          <div class="span9">&nbsp;</div>
        </div>
      </div> 
    </div>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Itpact</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css" />
  <script>
  $(function() {
    var spinner = $('#topbottom input').spinner();
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if admin_signed_in? %>
  <%= render "layouts/managebar" %>
  <% else %>
  <%= render "layouts/header" %>
  <% end %>



<div class="container">
  <div class="container">
    <div class="row">
  
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>
  </div></div></div>


  <div class="container">
    <div class="row">
      <div class="span12"><%= yield %></div>
    </div>
      
    </div>
  </body>
</html>